
export const ANIME_GET_FAVORITE_REQUEST = "ANIME_GET_FAVORITE_REQUEST" 
export const ANIME_GET_FAVORITE_SUCCESS = "ANIME_GET_FAVORITE_SUCCESS" 
export const ANIME_GET_FAVORITE_FAIL = "ANIME_GET_FAVORITE_FAIL" 

export const ANIME_GET_INFO_REQUEST = "ANIME_GET_INFO_REQUEST" 
export const ANIME_GET_INFO_SUCCESS = "ANIME_GET_INFO_SUCCESS" 
export const ANIME_GET_INFO_FAIL = "ANIME_GET_INFO_FAIL" 

export const ANIME_GET_RATING_REQUEST = "ANIME_GET_RATING_REQUEST" 
export const ANIME_GET_RATING_SUCCESS = "ANIME_GET_RATING_SUCCESS" 
export const ANIME_GET_RATING_FAIL = "ANIME_GET_RATING_FAIL" 

export const ANIME_GET_CATEGORIES_REQUEST = "ANIME_GET_CATEGORIES_REQUEST" 
export const ANIME_GET_CATEGORIES_SUCCESS = "ANIME_GET_CATEGORIES_SUCCESS" 
export const ANIME_GET_CATEGORIES_FAIL = "ANIME_GET_CATEGORIES_FAIL" 

export const ANIME_GET_EPISODE_REQUEST = "ANIME_GET_EPISODE_REQUEST" 
export const ANIME_GET_EPISODE_SUCCESS = "ANIME_GET_EPISODE_SUCCESS" 
export const ANIME_GET_EPISODE_FAIL = "ANIME_GET_EPISODE_FAIL" 

export const ANIME_GET_SEARCH_ANIME_REQUEST = "ANIME_GET_SEARCH_ANIME_REQUEST" 
export const ANIME_GET_SEARCH_ANIME_SUCCESS = "ANIME_GET_SEARCH_ANIME_SUCCESS" 
export const ANIME_GET_SEARCH_ANIME_FAIL = "ANIME_GET_SEARCH_ANIME_FAIL" 

export const ANIME_GET_HOME_REQUEST = "ANIME_GET_HOME_REQUEST" 
export const ANIME_GET_HOME_SUCCESS = "ANIME_GET_HOME_SUCCESS" 
export const ANIME_GET_HOME_FAIL = "ANIME_GET_HOME_FAIL"  